version: "3.1"

services:
    web:
        image: nginx:stable-alpine
        container_name: web
        working_dir: /var/www/app
        ports:
            - "8001:80"
        volumes:
            - .:/var/www/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    app:
        build:
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
        container_name: app
        working_dir: /var/www/app
        volumes:
            - .:/var/www/app
            - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

    mysql:
        image: mysql:5.7.22
        container_name: mysql
        working_dir: /var/www/app
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql:/etc/mysql/conf.d
        ports:
            - "3310:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
    redis:
        image: redis:5
        container_name: redis
        ports:
            - "6377:6379"

